version: "2"

services:
  postgres:
    ports:
      - "5432"
    image: "postgres:14"
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASS}"
      POSTGRES_DB: "${DATABASE_NAME}"

  init-web:
    image: bookstore-saas:latest
    environment:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASS: "${DATABASE_PASS}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
    command: ["./hack/migrate.sh"]
#    command: ["/bin/bash", "-xc", "until nc -zvw10 postgres 5432; do echo 'init-web: waiting for database...'; sleep 2; done && python manage.py migrate"]
    
  web:
    environment:
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASS: "${DATABASE_PASS}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
    ports:
      - "8000"
    image: bookstore-saas:latest
